import type { Candidate } from "./types";

export const DEMO_CANDIDATES: Candidate[] = [
  {
    id: "demo-lin",
    nickname: "林同学",
    gender: "男",
    department: "计算机科学与技术系",
    grade: "大二",
    avatarColor: "#76619a",
    locations: ["九食堂", "十食堂"],
    diet: "无",
    duration: 30,
    statusText: "安静吃饭",
    interests: ["羽毛球", "摄影"],
    bio: "下课后想简单吃个饭，不赶时间。",
    genderScope: "不限",
    reliability: 0.88,
    newUser: true,
  },
  {
    id: "demo-zhou",
    nickname: "周同学",
    gender: "女",
    department: "外国语学院",
    grade: "大一",
    avatarColor: "#c47783",
    locations: ["十一食堂", "十二食堂"],
    diet: "素食",
    duration: 45,
    statusText: "想聊聊天",
    interests: ["阅读", "看展"],
    bio: "最近在熟悉仙林，想找个人一起吃顿饭。",
    genderScope: "仅同性",
    reliability: 0.91,
  },
  {
    id: "demo-xu",
    nickname: "许同学",
    gender: "男",
    department: "物理学院",
    grade: "大三",
    avatarColor: "#4f8190",
    locations: ["学则路", "金鹰"],
    diet: "不吃辣",
    duration: 20,
    statusText: "赶时间",
    interests: ["跑步", "科幻"],
    bio: "晚点还有实验，吃饭会比较快。",
    genderScope: "不限",
    reliability: 0.84,
  },
  {
    id: "demo-shen",
    nickname: "沈同学",
    gender: "女",
    department: "商学院",
    grade: "大二",
    avatarColor: "#d18d56",
    locations: ["九食堂", "金鹰"],
    diet: "无",
    duration: 30,
    statusText: "随意",
    interests: ["桌游", "旅行"],
    bio: "可以边吃边聊，也可以安静吃饭。",
    genderScope: "不限",
    reliability: 0.86,
  },
  {
    id: "demo-chen",
    nickname: "陈同学",
    gender: "其他",
    department: "地理科学学院",
    grade: "大四",
    avatarColor: "#5d8b71",
    locations: ["十食堂", "十二食堂"],
    diet: "清真",
    duration: 45,
    statusText: "想聊聊天",
    interests: ["徒步", "音乐"],
    bio: "毕业前还在仙林，今天想认识一位饭友。",
    genderScope: "不限",
    reliability: 0.8,
    newUser: true,
  },
  {
    id: "demo-wang",
    nickname: "王同学",
    gender: "男",
    department: "数学系",
    grade: "大一",
    avatarColor: "#5572a4",
    locations: ["十一食堂", "学则路"],
    diet: "不吃辣",
    duration: 30,
    statusText: "随意",
    interests: ["篮球", "音乐"],
    bio: "刚下课，想找个饭搭子一起走。",
    genderScope: "不限",
    reliability: 0.82,
  },
];

export const INTEREST_OPTIONS = ["羽毛球", "阅读", "摄影", "音乐", "跑步", "看展", "桌游", "旅行"];
export const DEPARTMENT_OPTIONS = ["数学系", "计算机科学与技术系", "物理学院", "商学院", "外国语学院", "地理科学学院", "其他"];
